###
# Copyright (2017) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###
---
- name: Install wordpress-mysql
  hosts: local
  connection: local
  gather_facts: false

  vars_files:
    - ../group_vars/vars
    - ../group_vars/vault

  environment: "{{ env }}"

  tasks:

    - debug: msg="Starting Playbook wordpress-mysql"

    - name: Copy wordpress-mysql namespace template
      template:
        src: ../templates/wordpress-mysql/wordpress-mysql-namespace.yml.j2
        dest: /tmp/wordpress-mysql-namespace.yml


    - name: Copy mysql-pvc template
      template:
        src: ../templates/wordpress-mysql/mysql-pvc.yml.j2
        dest: /tmp/mysql-pvc.yml

    - name: Copy wordpress-pvc template
      template:
        src: ../templates/wordpress-mysql/wordpress-pvc.yml.j2
        dest: /tmp/wordpress-pvc.yml



    - include_tasks: includes/find_ucp.yml
      vars:
        ping_servers: "{{ groups.ucp }}"
    - debug: var=ucp_instance
      when: _debug is defined


    # Assume playbooks/install_client_bundle.yml has been run before this
    # Assume that ucp_instance hasn't changed in the meantime
    # - include_tasks: includes/config_client.yml

    - name: Apply yml files to install nfs provisioner
      shell: |
        . env.sh
        #kubectl apply -f /tmp/wordpress-mysql-namespace.yml
        #kubectl -n wordpress-mysql apply -f /tmp/mysql-pvc.yml
        kubectl -n wordpress-mysql apply -f /tmp/wordpress-pvc.yml
      args:
        chdir: ~/certs.{{ ucp_instance }}.{{ ucp_username }}
        executable: /usr/bin/bash
      register: ps

    - debug: var=ps.stdout_lines




